services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/frankenphp/Dockerfile
    container_name: mylego_collection_app
    restart: unless-stopped
    # run as root to allow TestContainers to start
    # DO NOT USE in production environments
    user: root
    volumes:
      - ../../back/src:/app/src
      - ../../back/tests:/app/tests
      - ../../back/config:/app/config
      - ../../back/coverage:/app/coverage
      - ../../back/migrations:/app/migrations
      - ../../back/templates:/app/templates
      - ../../back/public:/app/public
      - ../../back/composer.json:/app/composer.json
      - ../../back/composer.lock:/app/composer.lock
      - ../../back/.env:/app/.env
      - ../../back/.env.dev:/app/.env.dev
      - ../../back/.env.test:/app/.env.test
      - ../../back/phpunit.xml:/app/phpunit.xml
      # bad performance when mounting vendor on windows machines
      # - ../../back/vendor:/app/vendor
      # necessary to enable TestContainer to create containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CONFIG=client_host=host.docker.internal
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=mylego_collection
#      - POSTGRES_USER=mylego_collection
#      - POSTGRES_PASSWORD=mylego_collection_pass
#      - REDIS_URL=redis://mylego_collection_redis
      # - DOCKER_HOST=tcp://host.docker.internal:2375
    ports:
      - "8080:80"   # FrankenPHP
    depends_on:
      - db
      - redis
    networks:
      - mylego_collection_net

  db:
    image: postgres:16
    container_name: mylego_collection_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mylego_collection
      POSTGRES_USER: mylego_collection
      POSTGRES_PASSWORD: mylego_collection_pass
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - mylego_collection_net

  redis:
    image: redis:7
    container_name: mylego_collection_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mylego_collection_net

volumes:
  db_data:
  
networks:
  mylego_collection_net:
    driver: bridge