framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        default_bus: integration.bus

        buses:
            command.bus:
                default_middleware:
                    - validation
                    - doctrine_transaction
                    - dispatch_after_current_bus
                    -
            integration.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true

            auth.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - auth.integration_event_middleware

            user.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - user.integration_event_middleware

            collection-management.bus:
                default_middleware: allow_no_handlers

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourM': async
            'MyLegoCollection\SharedEvent\IntegrationEvent': async
            'MyLegoCollection\SharedEvent\Command': async
            # it's important the IdentityCreatedIntegrationEvent can also be handled immediately by some slices
            'MyLegoCollection\SharedEvent\IdentityCreatedIntegrationEvent': sync
            # it's important the UserCreatedIntegrationEvent can also be handled immediately by some slices
            'MyLegoCollection\SharedEvent\UserCreatedIntegrationEvent': sync



# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
