monolog:

    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: warning
            formatter: monolog.formatter.line
            channels: ["!event", "!doctrine"]

        doctrine:
            type: stream
            path: "php://stdout"
            level: error
            channels: [ "doctrine" ]

        messenger:
            type: stream
            path: "php://stdout"
            level: info
            channels: [ "messenger" ]
