user_controllers:
    resource:
        path: ../src/User/Infrastructure/Controller
        namespace: App\User\Infrastructure\Controller
    type: attribute
    format: json

collection_controllers:
    resource:
        path: ../src/CollectionManagement/Infrastructure/Controller
        namespace: App\CollectionManagement\Infrastructure\Controller
    type: attribute
    format: json
