# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: services/shared.yaml }
    - { resource: services/auth.yaml }
    - { resource: services/user.yaml }
    - { resource: services/collection-management.yaml }
    - { resource: services/notification.yaml }

parameters:
    public_upload_dir: '%kernel.project_dir%/public/uploads'
    public_upload_base_url: '%env(PUBLIC_UPLOAD_BASE_URL)%'
    frontends:
        app: '%env(FRONTEND_APP_URL)%'
    frontend_routes:
        app:
            home: ''
            confirm_identity: /account/confirm/:token
            account: /account
            collection: /collection

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more Service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\DataFixtures\:
        resource: '../src/DataFixtures/'


    App\Shared\Infrastructure\Service\FrontendUrlGenerator:
        arguments:
            $frontends: '%frontends%'
            $routes: '%frontend_routes%'


    _instanceof:
        # All services implementing the IntegrationEventHandler interface must use only the integration.bus
        App\Shared\Infrastructure\EventHandler\IntegrationEventHandler:
            tags:
                - { name: messenger.message_handler, bus: integration.bus }

        # All services implementing the CommandHandler interface must use only the command.bus
        App\Shared\Infrastructure\EventHandler\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }


when@test:
    parameters:
        public_upload_dir: '%kernel.project_dir%/var/test/upload'

    services:
        App\Tests\Utilities\DummySyncIntegrationEventHandler:
            public: true
            tags:
                - { name: 'messenger.message_handler', bus: integration.bus }

        App\Tests\Utilities\DummySyncCommandHandler:
            public: true
            tags:
                - { name: 'messenger.message_handler', bus: command.bus }
