services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Auth\Domain\:
        resource: '../../src/Auth/Domain/'
        exclude:
            - '../../src/Auth/Domain/Event'
            - '../../src/Auth/Domain/Exception'
            - '../../src/Auth/Domain/Model'

    App\Auth\Application\:
        resource: '../../src/Auth/Application/'
        exclude:
            - '../../src/Auth/Application/Command'

    App\Auth\Infrastructure\:
        resource: '../../src/Auth/Infrastructure/'
        exclude:
            - '../../src/Auth/Infrastructure/Dto'
            - '../../src/Auth/Infrastructure/Persistence/Doctrine/Entity'
            - '../../src/Auth/Infrastructure/Security/User'

    App\Shared\Domain\Port\Driven\EventBus: '@App\Auth\Infrastructure\Messenger\AuthEventBus'

    _instanceof:
        # All services implementing the DomainEventHandler interface
        # in the auth slice must use only the auth.bus
        App\Shared\Infrastructure\EventHandler\DomainEventHandler:
            tags:
                - { name: messenger.message_handler, bus: auth.bus }


