services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Notification\Domain\:
        resource: '../../src/Notification/Domain/'
        exclude:
            - '../../src/Notification/Domain/Event'
            - '../../src/Notification/Domain/Exception'
            - '../../src/Notification/Domain/Model'

    App\Notification\Application\:
        resource: '../../src/Notification/Application/'
        exclude:
            - '../../src/Notification/Application/Command'

    App\Notification\Infrastructure\:
        resource: '../../src/Notification/Infrastructure/'
        exclude:
            - '../../src/Notification/Infrastructure/Dto'
            - '../../src/Notification/Infrastructure/Persistence/Doctrine/Entity'
