services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\User\Domain\:
        resource: '../../src/User/Domain/'
        exclude:
            - '../../src/User/Domain/Event'
            - '../../src/User/Domain/Exception'
            - '../../src/User/Domain/Model'

    App\User\Application\:
        resource: '../../src/User/Application/'
        exclude:
            - '../../src/User/Application/Command'

    App\User\Infrastructure\:
        resource: '../../src/User/Infrastructure/'
        exclude:
            - '../../src/User/Infrastructure/Dto'
            - '../../src/User/Infrastructure/Persistence/Doctrine/Entity'

    App\Shared\Domain\Service\EventBus: '@App\User\Infrastructure\Messenger\UserEventBus'

    _instanceof:
        # All services implementing the DomainEventHandler interface
        # in the User slice must use only the user.bus
        App\Shared\Infrastructure\EventHandler\DomainEventHandler:
            tags:
                - { name: messenger.message_handler, bus: user.bus }
